name: Deploy to Lovable

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Create production environment
        run: |
          echo "VITE_CHAIN_ID=${{ vars.VITE_CHAIN_ID }}" >> .env.production
          echo "VITE_RPC_URL=${{ vars.VITE_RPC_URL }}" >> .env.production
          echo "VITE_WALLETCONNECT_PROJECT_ID=${{ secrets.VITE_WALLETCONNECT_PROJECT_ID }}" >> .env.production
          echo "VITE_ONCHAINKIT_API_KEY=${{ secrets.VITE_ONCHAINKIT_API_KEY }}" >> .env.production
          echo "VITE_COINBASE_PAYMASTER_RPC=https://api.developer.coinbase.com/rpc/v1/base/${{ secrets.COINBASE_API_KEY }}" >> .env.production
          
      - name: Build for production
        run: npm run build
        
      - name: Deploy to Lovable
        env:
          LOVABLE_TOKEN: ${{ secrets.LOVABLE_TOKEN }}
        run: |
          echo "🚀 Deploying to Lovable..."
          # TODO: Ajoutez ici les commandes spécifiques pour déployer sur Lovable
          # Exemple basique (à adapter selon l'API Lovable) :
          # npx lovable deploy --token $LOVABLE_TOKEN --build-dir ./dist
          echo "✅ Deployment configured - add Lovable CLI commands here"
          
      - name: Clean up environment files
        run: |
          rm -f .env.production
          
      - name: Notify deployment status
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "✅ Deployment to Lovable successful!"
          else
            echo "❌ Deployment to Lovable failed!"
          fi